server {
  listen 80;
  server_name localhost;

  # static files
  location /uploads/ {
    alias /var/www/uploads/;
    try_files $uri $uri/ =404;
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }

  # proxy on backend
  location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://backend-bun:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
