
import __ASTRO_IMAGE_IMPORT_1XsnEe from "/src/assets/images/members/john-doe.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_Z1UkBp0 from "/src/assets/images/members/jane-smith.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_xLxOS from "/src/assets/images/members/alice-jones.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_2tuF96 from "/src/assets/images/members/bob-brown.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_Hdh6B from "/src/assets/images/members/carol-white.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_1RFKkK from "/src/assets/images/members/dave-black.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json";
import __ASTRO_IMAGE_IMPORT_1PKGKT from "/src/assets/images/pets/cats/captain-meow.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_ZRGwYG from "/src/assets/images/pets/cats/catrick-swayze.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_BhCFQ from "/src/assets/images/pets/cats/clawdia.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_ZVFowb from "/src/assets/images/pets/cats/furrball-mcwhiskers.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_gMuTh from "/src/assets/images/pets/cats/pawdre-hepburn.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_Z1U6byN from "/src/assets/images/pets/cats/purrlock-holmes.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_1TC2Hx from "/src/assets/images/pets/cats/reckoning.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_1OviNK from "/src/assets/images/pets/cats/sir-pounce-a-lot.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_2lJyyC from "/src/assets/images/pets/cats/whiskerfield-stallone.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json";
import __ASTRO_IMAGE_IMPORT_jHrOL from "src/assets/images/pexels-thirdman-8942612.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnew-site-launched.md";
import __ASTRO_IMAGE_IMPORT_ZxcET8 from "src/assets/images/pexels-chevonrossouw-2558605.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhello-world.md";
import __ASTRO_IMAGE_IMPORT_Z2rs0bs from "src/assets/images/pexels-minan1398-1003994.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnew-cat.md";
export default new Map([["/src/assets/images/members/john-doe.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_1XsnEe], ["/src/assets/images/members/jane-smith.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_Z1UkBp0], ["/src/assets/images/members/alice-jones.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_xLxOS], ["/src/assets/images/members/bob-brown.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_2tuF96], ["/src/assets/images/members/carol-white.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_Hdh6B], ["/src/assets/images/members/dave-black.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fmembers.json", __ASTRO_IMAGE_IMPORT_1RFKkK], ["/src/assets/images/pets/cats/captain-meow.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_1PKGKT], ["/src/assets/images/pets/cats/catrick-swayze.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_ZRGwYG], ["/src/assets/images/pets/cats/clawdia.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_BhCFQ], ["/src/assets/images/pets/cats/furrball-mcwhiskers.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_ZVFowb], ["/src/assets/images/pets/cats/pawdre-hepburn.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_gMuTh], ["/src/assets/images/pets/cats/purrlock-holmes.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_Z1U6byN], ["/src/assets/images/pets/cats/reckoning.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_1TC2Hx], ["/src/assets/images/pets/cats/sir-pounce-a-lot.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_1OviNK], ["/src/assets/images/pets/cats/whiskerfield-stallone.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fanimals.json", __ASTRO_IMAGE_IMPORT_2lJyyC], ["src/assets/images/pexels-thirdman-8942612.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnew-site-launched.md", __ASTRO_IMAGE_IMPORT_jHrOL], ["src/assets/images/pexels-chevonrossouw-2558605.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhello-world.md", __ASTRO_IMAGE_IMPORT_ZxcET8], ["src/assets/images/pexels-minan1398-1003994.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnew-cat.md", __ASTRO_IMAGE_IMPORT_Z2rs0bs]]);
		